# version: "3.7"
version: "3.9"

services:
  pokus_dev:
    # we need extended, and nodejs for sass!
    image: pokusio/jb-lasselle-whoami-web:${QUAY_OCI_IMAGE_TAG}-dev
    # container_name: pokus_dev
    build:
       context: .
       dockerfile: dev.Dockerfile
       args:
         - POKUS_USER_NAME=$POKUS_USER_NAME
         - POKUS_USER_GRPNAME=$POKUS_USER_GRPNAME
         - POKUS_USER_UID=$POKUS_USER_UID
         - POKUS_USER_GID=$POKUS_USER_GID
         - ALPINE_OCI_IMAGE_TAG=${ALPINE_OCI_IMAGE_TAG}
         - GOLANG_VERSION=${GOLANG_VERSION}
         - HUGO_VERSION=${HUGO_VERSION}
         - GIT_COMMIT_ID=${GIT_COMMIT_ID}
         - CICD_BUILD_ID=${CICD_BUILD_ID}
         - CICD_BUILD_TIMESTAMP=${CICD_BUILD_TIMESTAMP}
         - QUAY_OCI_IMAGE_TAG=${QUAY_OCI_IMAGE_TAG}
    volumes:
      - type: bind
        source: ./static
        target: /opt/app/staticvolumes:
    env_file:
      - ./.dev.env
