# version: "3.7"
version: "3.9"

services:
  pokus_dev:
    # we need extended, and nodejs for sass!
    image: pokusio/jb-lasselle-whoami-web:${QUAY_OCI_IMAGE_TAG}-dev
    # container_name: pokus_dev
    volumes:
      - type: bind
        source: ./../../
        target: /opt/app/staticvolumes:
    env_file:
      - ./.dev.env
